name: rydmikesplash
description: "A new flutter project."
publish_to: 'none'
version: 0.1.0

envirorment:
sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flex_color_scheme: ^8.2.0
  google_fonts: ^6.3.1
  firebase_core: ^3.0.0
  cloud_firestore: ^5.6.12

dev_dependencies:
flutter_test:
 sdk: flutter
flutter_lints: ^5.0.0

flutter:
uses-material-design: true
